### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by apinner84** [br-automation-com/mappDatabase-Demo#6]
Hi @stephan1827 

We're using your modified Python script with our own database fb. We're getting an issue where the python db connector is closing the connection after 60 seconds because of the configured http timeout. However, mpdatabase on the PLC is unaware the connection has closed and still believes it is connected. 

Should we be connecting and disconnecting after executing each query or is there something obvious I am missing?

**Comment by stephan1827** [comment]
Hi @apinner84,
I think that is just the way it works. The mappDatabase library automatically reconnects when the connection is closed.

![image](https://user-images.githubusercontent.com/2972703/162190257-f538e438-4142-4c3f-b0df-3811c41c5ad0.png)

**Comment by apinner84** [comment]
Here is a snip of what we are experiencing.
![dbconnector](https://user-images.githubusercontent.com/69159945/162208933-339b03f9-9b1e-40f3-aa54-a779bd5c0dcc.PNG)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/69159945/162208967-592ed688-4f49-491c-b6ce-a514332df05b.png)

Timeout happened at 14:11:51
PLC tried to execute a query at 14:22:15 that ends in exception code1

**Comment by stephan1827** [comment]
What mapp version are you using?

Can you try to set "Connect" back to false when you are connected? Thats what is different from my sample and I also noticed that the CommandDone flag goes back to false in my sample. I am not sure if that makes a difference but its worth a whot.
![image](https://user-images.githubusercontent.com/2972703/162214450-1c8777a2-c228-4c7c-ba77-21a223cfa968.png)

**Comment by apinner84** [comment]
We're using 5.16

I'll try that modification first. It's also possible that it's being caused by a download to the PLC.

**Comment by stephan1827** [comment]
Yes, you always should restart the PLC after changing anything in mapp. The mapp link is expired and will cause weird behavior. Calling it in the exit part of the task sometimes helps, but a restart is the safest option.

**Comment by apinner84** [comment]
Haven't spotted the issue since making your suggested changes. Thanks.
