### ISSUE TITLE
SQL Error 10054

### ISSUE THREAD

**Issue by apinner84** [br-automation-com/mappDatabase-Demo#7]
Hi @stephan1827 

This is not necessarily an issue with the python connector but one it may be able to solve. We're using the connector on three separate machines all three are querying the same database. Two of them are querying very often, every few seconds and we're seeing a 10054 error on the connector every day or so. It's a socket error, essentially it looks like the connector is attempting to use a socket that has been closed. Microsoft suggest this is being terminated at the server side, but we can find no evidence of this. 

We've ran network diagnostics, traces, looked for packet loss, checked event logs, checked SQL server logs. We're unable to find the cause of the issue at the moment. 

Do you know what would be involved in handling the error, and opening a new connection/socket in the python if the socket is closed?

**Comment by stephan1827** [comment]
Do you know where this error is fired in the script? What happens after this error? Is the connection broken, or does the next request go through?

**Comment by stephan1827** [comment]
I am sorry, but I am afraid you have to go through the official B&R support for this. If there is an issue that is related to the modified python script or the sample, I am happy to look into this, but if you can reproduce the same issue with the standard script from the help file it has to go back to B&R.

**Comment by apinner84** [comment]
Understood, we get the issue on both versions I believe. I will try contacting our UK support.
